import { Theme, ThemeName } from "../types";

export const themes: Record<ThemeName, Theme> = {
  aubergine: {
    name: "aubergine",
    colors: {
      background: "#1A0B1C",
      surface: "#FDF8F2",
      primary: "#2D0A31",
      accent: "#C9A8D4",
      text: "#FDF8F2",
      textSecondary: "#B895C9",
      border: "#4A2C4A",
      cta: "#C87D53",
      tabBar: "#1A0B1C",
      tabBarActive: "#C9A8D4",
      tabBarInactive: "#4A2C4A",
      statusBar: "light",
    },
  },
  rose: {
    name: "rose",
    colors: {
      background: "#1C0B0F",
      surface: "#FDF5F5",
      primary: "#2D0A12",
      accent: "#E8B4B8",
      text: "#FDF5F5",
      textSecondary: "#D4A0A5",
      border: "#4A2528",
      cta: "#C87D6B",
      tabBar: "#1C0B0F",
      tabBarActive: "#E8B4B8",
      tabBarInactive: "#4A2528",
      statusBar: "light",
    },
  },
  midnight: {
    name: "midnight",
    colors: {
      background: "#0A1128",
      surface: "#F2F4FA",
      primary: "#0D1B4A",
      accent: "#A8C4E0",
      text: "#F2F4FA",
      textSecondary: "#8BA4C7",
      border: "#1E3050",
      cta: "#C8963E",
      tabBar: "#0A1128",
      tabBarActive: "#A8C4E0",
      tabBarInactive: "#1E3050",
      statusBar: "light",
    },
  },
  sandalwood: {
    name: "sandalwood",
    colors: {
      background: "#1C1408",
      surface: "#FDF9F0",
      primary: "#2D1F0A",
      accent: "#D4C5A0",
      text: "#FDF9F0",
      textSecondary: "#C4B38A",
      border: "#4A3C20",
      cta: "#C87D3E",
      tabBar: "#1C1408",
      tabBarActive: "#D4C5A0",
      tabBarInactive: "#4A3C20",
      statusBar: "light",
    },
  },
  jasmine: {
    name: "jasmine",
    colors: {
      background: "#0B1C0F",
      surface: "#F2FDF5",
      primary: "#0A2D12",
      accent: "#A8D4B8",
      text: "#F2FDF5",
      textSecondary: "#8AC79D",
      border: "#204A28",
      cta: "#6BC87D",
      tabBar: "#0B1C0F",
      tabBarActive: "#A8D4B8",
      tabBarInactive: "#204A28",
      statusBar: "light",
    },
  },
};

export const themeLabels: Record<ThemeName, string> = {
  aubergine: "Aubergine Luxe",
  rose: "Rose Quartz",
  midnight: "Midnight Oud",
  sandalwood: "Sandalwood Warm",
  jasmine: "Jasmine Mist",
};
